class Stepper:
    def __init__(self, pins: list[int], steps: int) -> None: ...
    def step(self, direction: bool, level: float) -> int: ...
    def stop(self) -> None: ...
    def __del__(self) -> None: ...

class DiffDrive:
    def __init__(self, rpins: list[int], lpins: list[int], steps: int) -> None: ...
    def task_loop(self) -> None: ...
    def stop(self) -> None: ...
    def set_rpm(self, rrpm: float, lrpm: float) -> None: ...
    def set_trans_rot(self, trans: float, rot: float) -> None: ...
    def __del__(self) -> None: ...
